### ISSUE TITLE
Old county JSONs

### ISSUE THREAD

**Issue by jason-lange** [simonw/cdc-vaccination-history#3]
Hi, do you archive the prior JSONs for the county vaccination data? I only see the latest here. Thanks!

**Comment by simonw** [comment]
You can get to the older ones from this list here: https://github.com/simonw/cdc-vaccination-history/commits/main/counties.json

<img width="1012" alt="History_for_counties_json_-_simonw_cdc-vaccination-history" src="https://user-images.githubusercontent.com/9599/134063686-ff0acee1-0b10-48f5-8b74-292d247c4d94.png">

Use the "Browse the repository at this point in the history" link and then click on `counties.json`.
