### ISSUE TITLE
How do you download the full data set?

### ISSUE THREAD

**Issue by BenjaminKay** [simonw/cdc-vaccination-history#4]
I am using the link provided: https://cdc-vaccination-history.datasette.io/cdc/daily_reports_counties
Under CSV options I check off  "download file" and  "stream all rows", and then click on "export csv".  I get the following error:

> An error occurred with your deployment
> 
> 504: GATEWAY_TIMEOUT Code: FUNCTION_INVOCATION_TIMEOUT ID: iad1::xd25w-1621449834980-16b0300f009e
> 
>     If you are a visitor, contact the website owner or try again later.
>     If you are the owner, check the logs for the application error. 

Is there another way you could just post the whole file? Like maybe a separate git hub repository could hold the results?

**Comment by seawavevan** [comment]
I also ran into the same issue when I tried to download the full dataset. Is there any other way to download this data?

> I am using the link provided: https://cdc-vaccination-history.datasette.io/cdc/daily_reports_counties
> Under CSV options I check off "download file" and "stream all rows", and then click on "export csv". I get the following error:
> 
> > An error occurred with your deployment
> > 504: GATEWAY_TIMEOUT Code: FUNCTION_INVOCATION_TIMEOUT ID: iad1::xd25w-1621449834980-16b0300f009e
> > ```
> > If you are a visitor, contact the website owner or try again later.
> > If you are the owner, check the logs for the application error. 
> > ```
> 
> Is there another way you could just post the whole file? Like maybe a separate git hub repository could hold the results?

**Comment by BenjaminKay** [comment]
I believe this issue can be fixed by increasing changing the start.sh options on the hosting server. In particular, increasing the value on "setting sql_time_limit_ms" Something like this:

  datasette .data/data.db \
    -p 3000 \
    -m metadata.yml  \
    --cors \
    --config default_cache_ttl:0 \
    --setting default_page_size 5000 \
    --setting sql_time_limit_ms 35000 \
    --setting max_returned_rows 20000

**Comment by alexose** [comment]
It might be nice to publish a 'condensed' version straight to github, too.  Similar to the nytimes data:

https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv

Edit:   Went ahead and did this here: https://github.com/simonw/cdc-vaccination-history/pull/5

**Comment by simonw** [comment]
I'm currently migrating the site to Cloud Run which should enable full data downloads again.

**Comment by simonw** [comment]
This should work now, but the performance isn't great. I'm going to start publishing a CSV version of the full data too.
