### ISSUE TITLE
Publish CSV versions of the data as well

### ISSUE THREAD

**Issue by simonw** [simonw/cdc-vaccination-history#9]
_Originally posted by @simonw in https://github.com/simonw/cdc-vaccination-history/issues/4#issuecomment-923243575_

Also inspired by PR #5 by @alexose

**Comment by simonw** [comment]
I'm going to use a Google Cloud bucket for this.

**Comment by simonw** [comment]
I created the bucket like this:

    gsutil mb gs://cdc-vaccination-history-csv.datasette.io/

Then I set it so that anyone can read from it, following the instructions on https://cloud.google.com/storage/docs/hosting-static-website-http#gsutil

    gsutil iam ch allUsers:objectViewer gs://cdc-vaccination-history-csv.datasette.io

And I pointed DNS at it - `CNAME` of `cdc-vaccination-history-csv` pointed at `c.storage.googleapis.com.` configured at https://vercel.com/dashboard/domains/datasette.io

<img width="1141" alt="datasette_io_-_Domains_–_Vercel" src="https://user-images.githubusercontent.com/9599/134065994-32e68275-db1e-4a75-835e-fbeae535119c.png">

**Comment by simonw** [comment]
To generate the CSV files I used:

    sqlite-utils cdc.db 'select * from daily_reports_counties' --csv > daily_reports_counties.csv
    sqlite-utils cdc.db 'select * from daily_reports' --csv > daily_reports.csv

Then I copied them to the bucket with:

    gsutil cp *.csv gs://cdc-vaccination-history-csv.datasette.io

**Comment by simonw** [comment]
Wrote this up as a TIL: https://til.simonwillison.net/googlecloud/gsutil-bucket

**Comment by simonw** [comment]
This now happens automatically every time the workflow runs: https://github.com/simonw/cdc-vaccination-history/blob/59454983cf804d557ab367c719a70f922de980ab/.github/workflows/scrape.yml#L51-L57

**Comment by alexose** [comment]
Looks great! I like this approach a lot.
